### ISSUE TITLE
TypeScript but do not have typescript installed.

### ISSUE THREAD

**Issue by Sooraj-s-98** [UI-books/react-template#18]
@spantheslayer 

npm start

> game-of-life@0.1.0 start C:\Users\91963\git repo\react-template\Template\Game-of-life
> react-scripts start

It looks like you're trying to use TypeScript but do not have typescript installed.
Please install typescript by running npm install typescript.
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files).

npm install typescript.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/typescript. - Not found
npm ERR! 404
npm ERR! 404  'typescript.@latest' is not in the npm registry.

**Comment by spantheslayer** [comment]
hey @Sooraj-s-98 did u do `npm install` before runninng the project ? 
if not follow the steps 
1.  `npm install`
2.  `npm start`

**Comment by Sooraj-s-98** [comment]
Same steps
 executed.
Error.
So
 npm install typescript
Same problem

**Comment by spantheslayer** [comment]
hey can u give the npm log with sreenshot ?

**Comment by Sooraj-s-98** [comment]
@spantheslayer 
![image](https://user-images.githubusercontent.com/52352285/96849445-39e47480-1473-11eb-8e7c-9d68cad8aa7c.png)

**Comment by spantheslayer** [comment]
Like I said , Can U please share the logs ? Copy the whole error log from the cmd and pase it here within two backticks

**Comment by spantheslayer** [comment]
1.  `export NODE_ENV=production`
2. `npm start`

and show me the logs , this should work on you machine

**Comment by Sooraj-s-98** [comment]
it is not solution. it is nodemon problem. corrected

**Comment by spantheslayer** [comment]
hey I never used nodemon in this library . i think you are making some mistakes and also it runs perfectly on my machine and others . what is yor node version and why dont u show me the logs , I can fix your issue
