### ISSUE TITLE
Module not found: Can't resolve 'immer'

### ISSUE THREAD

**Issue by Sooraj-s-98** [UI-books/react-template#21]
@spantheslayer 
Module not found: Can't resolve 'immer' in 'C:\Users\..........\git repo\react-template\Template\Game-of-life\src'
![image](https://user-images.githubusercontent.com/52352285/96864862-baf93700-1486-11eb-8e7a-bd177ea9b8b1.png)

**Comment by spantheslayer** [comment]
Hey , you did not install  the required packages properly , the `immer` module is a dependency that I installed . and so in `app.tsx` i imported the module . first do a proper installation of all the dependencies and then try `npm start`

**Comment by Sooraj-s-98** [comment]
Why are you using typescript?😅

**Comment by spantheslayer** [comment]
Hey , Typescript is better than javascript and it also gives the ability to use type features which by the name u can guess . and it also works great with react . 

if you are still getting the error , post the proper logs or close this issue :)

**Comment by Sooraj-s-98** [comment]
1. delete node modules
2. cmd 
3. `npm cache clear -f'
4. 'npm install'
5. 'npm audit fix'
6. 'npm start`
